### ISSUE TITLE
What does this project do differently?

### ISSUE THREAD

**Issue by prassanna-ravishankar** [YU-Zhiyang/opencv_transforms_torchvision#11]
There has been a project (which is already available in pip) : https://github.com/jbohnslav/opencv_transforms . What does this project aim to do differently?

**Comment by hityzy1122** [comment]
> There has been a project (which is already available in pip) : https://github.com/jbohnslav/opencv_transforms . What does this project aim to do differently?

Firstly, I build this project just for personal practice. Besides that, a few functions in jbohnslav's project are partly still based on PIL("adjust_saturation" for example),and mine are fully based on opencv or numpy.What's more, I debug the affine transform and add affine6 instead, and some new image process method are also included in my lib (some functions about adding noise for example)

**Comment by prassanna-ravishankar** [comment]
:+1:
