### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by victorca25** [YU-Zhiyang/opencv_transforms_torchvision#12]
This is not an issue, just to let you know that I combined your repo with https://github.com/jbohnslav/opencv_transforms and additional augmentations using OpenCV from one of my repos.

I tried to keep the best from all sources, use only OpenCV or np functions and extend functionality where possible.

In case you are interested, maybe in the additional transformations like noise types and blur, here's the repo: https://github.com/victorca25/opencv_transforms should be able to easily pull from it, as I merged the commit history of his and your repo.

**Comment by hityzy1122** [comment]
> This is not an issue, just to let you know that I combined your repo with https://github.com/jbohnslav/opencv_transforms and additional augmentations using OpenCV from one of my repos.
> 
> I tried to keep the best from all sources, use only OpenCV or np functions and extend functionality where possible.
> 
> In case you are interested, maybe in the additional transformations like noise types and blur, here's the repo: https://github.com/victorca25/opencv_transforms should be able to easily pull from it, as I merged the commit history of his and your repo.

Good job!
